# Generated by Django 4.1 on 2023-07-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_homeevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeEvent',
        ),
    ]
