# Generated by Django 4.1 on 2023-07-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='homeevent',
            options={'ordering': ['-start_date']},
        ),
    ]
