# Generated by Django 4.1 on 2023-07-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_homeblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeBlog',
        ),
    ]
