# Generated by Django 4.1 on 2023-07-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0017_ministrycategory_ministry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ministry',
        ),
        migrations.DeleteModel(
            name='Ministrycategory',
        ),
    ]
