# Generated by Django 4.1 on 2023-07-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0020_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
