# Generated by Django 4.1 on 2023-07-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0024_pastor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pastor',
        ),
    ]
