# Generated by Django 4.1 on 2023-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0028_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastor',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='pastor',
            name='gmail',
            field=models.URLField(blank=True),
        ),
    ]
