# Generated by Django 4.1 on 2023-09-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0027_remove_contact_subject_alter_contact_phone'),
        ('church', '0030_payment'),
    ]

    operations = [
    ]
