# Generated by Django 4.1 on 2023-07-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0032_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
