# Generated by Django 4.1 on 2023-10-31 22:21

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0032_payment_phone_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
